import { useState } from 'react'
import './App.css'
import AppView from './AppView'
import { useEntries } from './hooks/useEntries'

function App() {
  const [view, setView] = useState('table')
  const {
    formData,
    showCreateModal,
    confirmDialog,
    editingId,
    editData,
    searchName,
    filterStatus,
    filterPriority,
    sortConfig,
    pageSize,
    currentPage,
    selectionMode,
    selectedIds,
    statusOptions,
    statusLabels,
    priorityOptions,
    priorityLabels,
    pageCount,
    totalEntries,
    statusData,
    priorityData,
    statusGradient,
    priorityGradient,
    sortedFilteredEntries,
    paginatedEntries,
    resetFilters,
    toggleSelectionMode,
    handleSelectEntry,
    handleDeleteSelected,
    handleSort,
    handleFormChange,
    handleEditChange,
    openCreateModal,
    closeCreateModal,
    handleCreateEntry,
    handleDeleteEntry,
    startEditing,
    saveEditing,
    cancelEditing,
    setSearchName,
    setFilterStatus,
    setFilterPriority,
    setPageSize,
    setCurrentPage,
    toggleSelectPage,
    closeConfirmDialog,
    handleConfirmDialog,
  } = useEntries()

  return (
    <AppView
      {...{
        view,
        setView,
        selectionMode,
        toggleSelectionMode,
        handleSelectEntry,
        selectedIds,
        handleDeleteSelected,
        resetFilters,
        openCreateModal,
        searchName,
        setSearchName,
        filterStatus,
        setFilterStatus,
        filterPriority,
        setFilterPriority,
        statusOptions,
        statusLabels,
        priorityOptions,
        priorityLabels,
        toggleSelectPage,
        handleSort,
        sortConfig,
        sortedFilteredEntries,
        paginatedEntries,
        editingId,
        editData,
        handleEditChange,
        startEditing,
        handleDeleteEntry,
        saveEditing,
        cancelEditing,
        pageSize,
        setPageSize,
        setCurrentPage,
        currentPage,
        pageCount,
        totalEntries,
        statusGradient,
        statusData,
        priorityGradient,
        priorityData,
        showCreateModal,
        handleCreateEntry,
        formData,
        handleFormChange,
        closeCreateModal,
        confirmDialog,
        closeConfirmDialog,
        handleConfirmDialog,
      }}
    />
  )
}

export default App

